# Generated by Django 4.1.1 on 2022-10-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='acess_token',
            new_name='access_token',
        ),
    ]
